### ISSUE TITLE
Google Meet link incorrect

### ISSUE THREAD

**Issue by di** [ossf/wg-security-tooling#11]
Currently [the README](https://github.com/ossf/wg-security-tooling/blame/d669e48d681aac43191059d728b997a5755d85a9/README.md#L27) links to `https://meet.google.com/jgy-nenx-aok` but the calendar has `https://meet.google.com/unz-fyni-umj` as the meeting link.

**Comment by psiinon** [comment]
@di I've only just added the meeting to the OSSF Calendar, and that has the same link as the README.
What date/time are you seeing the 'other' meeting?

**Comment by di** [comment]
Sorry, I thought this was the same as the "Securing Critical Projects WG" meeting.
