### ISSUE TITLE
Verification of findings

### ISSUE THREAD

**Issue by fcanogab** [ossf/wg-security-tooling#17]
Hi!
Open source maintainers usually receive a lot of feedback about vulnerabilities found by security tools in open source projects. Sometimes, the quality of the information provided is not very good, and it generates a lot of work for the open source maintainer that maybe could be avoided.
I would like to propose to work, maybe within this working group, on this issue.
I'm thinking about:
- A checklist before reporting. What you have to check before sending a finding from a security tool to an open source project maintainer.
- A template for reporting. What it is interesting that you include in your report.
- Improvements of security tooling. What developers of security tools can do to improve the information of their findings.
What do you think?

**Comment by greysteil** [comment]
That sounds like a great project, but perhaps better suited to the [Vulnerability Disclosures working group](https://github.com/ossf/wg-vulnerability-disclosures)?

**Comment by fcanogab** [comment]
> That sounds like a great project, but perhaps better suited to the [Vulnerability Disclosures working group](https://github.com/ossf/wg-vulnerability-disclosures)?

Maybe! :) I think this project would be focused on the results that tools generate, understand them, verify them and work on them before reporting them to the open source maintainer. That's why I thought this was the best wg. I think the Vulnerability Disclosures wg work is more about how to disclose vulnerabilities to the public, for example CVEs, CVSS...I think they are farther from the tools.

What do you think?

**Comment by greysteil** [comment]
Ah, sorry, I hadn't realised your focus here was on results that tools generate. This group sounds like as good a place to discuss as any - please do join one of our calls! (Cc @psiinon)

**Comment by MarcinHoppe** [comment]
@fcanogab this is Marcin from the Vulnerability Disclosures WG. We are very much interested in all the topics that have to do with disclosing vulnerability data, including making this information as usable as possible.

Feel free to open an issue in our repo or start a thread on the mailing list!

**Comment by psiinon** [comment]
As the developer of an open source security tool I'm very interested in this :)
I dont really mind which WG it comes under - you could easily argue either way.
Its worth pointing out that security tools often have different users and use cases.
We know that ZAP is used by both devs and security folks and that their requirements are different.
Devs typically want highly actionable feedback. Pentesters often want any clues they can get about an app and dont mind if those findings need to be manually verified.
Running a ZAP scan and just sending the devs the HTML report is definitely not recommended :)

**Comment by david-a-wheeler** [comment]
> Running a ZAP scan and just sending the devs the HTML report is definitely not recommended :)

You smile, but the Linux kernel developers have reported to me that they're inundated with low-quality fuzzer output instead of something they can use.

**Comment by psiinon** [comment]
Oh I agree its a problem, but you have to understand that tools can be aimed at more than one set of people.
We want ZAP to be useful to both developers and pentesters. Working out how to expose the right functionality to the right set of users is really non trivial.

**Comment by fcanogab** [comment]
I thought that maybe this movement could fit in the vulnerability disclosures wg. However I talked about it a bit in the last wg meeting and I think maybe the objective or the actions are not well defined.
I think it is better to just close it now and maybe work on it from within other initiatives.
Thanks!
