### ISSUE TITLE
Add Meeting Invites to Public Calendar

### ISSUE THREAD

**Issue by dlorenc** [ossf/wg-security-tooling#9]
Could the meeting invites for this WG be added to the community calendar? Info is here: https://github.com/ossf/tac/issues/18

LMK if you need permissions or anything.

**Comment by psiinon** [comment]
@dlorenc happy to do this but it looks like I dont have the right perms.
I can use either psiinon@gmail.com or simon.bennetts@owasp.org

**Comment by LindsayLF** [comment]
Hi @psiinon - You are now an admin on the OpenSSF Public google calendar: 
https://calendar.google.com/calendar/u/0?cid=czYzdm9lZmhwNWk5cGZsdGI1cTY3bmdwZXNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by LindsayLF** [comment]
@dlorenc this issue can be closed.

**Comment by psiinon** [comment]
Thanks @LindsayLF - I've copied the meeting across.
